In [3]:
# Import pandas
import pandas as pd
import numpy as np
 
# reading csv file
data1 = pd.read_csv("forex_rate.csv")
df = pd.DataFrame(data1)
# reading csv file
data2 = pd.read_csv("canalys_smartphone_model_level_estimates.csv")
df2 = pd.DataFrame(data2)
#df4 = df.merge(df2[['Market', 'Currency']])
df4 = df.merge(df2[['Market', 'Currency','List price (local)']])

df4["USD$"] = df4["List price (local)"]/df4["Exchange rate"]
df4["VAT_in_$"] = df4["VAT"]*df4["USD$"]/100
df4["List price(US$) ex VAT"] = df4["USD$"]-df4["VAT_in_$"] 
df4
df5 = df4.to_csv(r'C:\Users\Keshav Pathak\Desktop\dataframeUSD.csv', index = False, header=True)

C:\Users\Keshav Pathak\AppData\Local\Temp\ipykernel_10380\4129243033.py:9: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  data2 = pd.read_csv("canalys_smartphone_model_level_estimates.csv")

In [4]:
df4

,Region,Sub-region,Market,Currency,Exchange rate,VAT,List price (local),USD$,VAT_in_$,List price(US$) ex VAT
0,Asia Pacific (excludes Greater China),Asia Pacific (excludes Greater China),Australia,AUD,1.419,0.1,635,447.498238,0.447498,447.050740
1,Asia Pacific (excludes Greater China),Asia Pacific (excludes Greater China),Australia,AUD,1.419,0.1,636,448.202960,0.448203,447.754757
2,Asia Pacific (excludes Greater China),Asia Pacific (excludes Greater China),Australia,AUD,1.419,0.1,647,455.954898,0.455955,455.498943
3,Asia Pacific (excludes Greater China),Asia Pacific (excludes Greater China),Australia,AUD,1.419,0.1,798,562.367865,0.562368,561.805497
4,Asia Pacific (excludes Greater China),Asia Pacific (excludes Greater China),Australia,AUD,1.419,0.1,857,603.946441,0.603946,603.342495
...,...,...,...,...,...,...,...,...,...,...
107835,North America,North America,United States,USD,1.000,0.0,450,450.000000,0.000000,450.000000
107836,North America,North America,United States,USD,1.000,0.0,99,99.000000,0.000000,99.000000
107837,North America,North America,United States,USD,1.000,0.0,40,40.000000,0.000000,40.000000
107838,North America,North America,United States,USD,1.000,0.0,50,50.000000,0.000000,50.000000
107839,North America,North America,United States,USD,1.000,0.0,150,150.000000,0.000000,150.000000